id: A49F1408C
base_file: fF2D5.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.827308
  last_modified_at: 2022-06-05 20:20:43.827311
