id: A49F1408C
base_file: fDAAA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.823063
  last_modified_at: 2022-06-05 20:20:43.823066
