id: A49F1408C
base_file: f6ABD.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.803963
  last_modified_at: 2022-06-05 20:20:43.803968
