id: A49F1408C
base_file: fF66B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.828375
  last_modified_at: 2022-06-05 20:20:43.828378
