id: A49F1408C
base_file: fB590.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.811455
  last_modified_at: 2022-06-05 20:20:43.811457
