id: A49F1408C
base_file: fF9A4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.831618
  last_modified_at: 2022-06-05 20:20:43.831621
