id: A49F1408C
base_file: f1264.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.766688
  last_modified_at: 2022-06-05 20:20:43.766694
