id: A49F1408C
base_file: f05C2.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.761920
  last_modified_at: 2022-06-05 20:20:43.761927
