id: A49F1408C
base_file: f635D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:20:43.799757
  last_modified_at: 2022-06-05 20:20:43.799762
